config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :kitchen
  resources :food_orders
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/food_order.rb
class FoodOrder < ApplicationRecord
  belongs_to :food
  belongs_to :order
  validates :quantity, :status, presence: true
end

app/controllers/food_orders_controller.rb
class FoodOrdersController < ApplicationController
  before_action :set_food_order, only: [:show, :edit, :update, :destroy]

  # GET /food_orders
  # GET /food_orders.json
  # def index
  #   @food_orders = FoodOrder.all
  # end

  # GET /food_orders/1
  # GET /food_orders/1.json

  def show

  end

  # GET /food_orders/new
  # def new
  #   @food_order = FoodOrder.new
  # end

  # GET /food_orders/1/edit

  # POST /food_orders
  # POST /food_orders.json
  def create
    @food_order = FoodOrder.new(food_order_params)

    respond_to do |format|
      if @food_order.save
        format.html { redirect_to @food_order, notice: 'Food order was successfully created.' }
        format.json { render :show, status: :created, location: @food_order }
      else
        format.html { render :new }
        format.json { render json: @food_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_orders/1
  # PATCH/PUT /food_orders/1.json
  def update
    respond_to do |format|
      if @food_order.update(food_order_params)
        format.html { redirect_to @food_order, notice: 'Food order was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_order }
      else
        format.html { render :edit }
        format.json { render json: @food_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_orders/1
  # DELETE /food_orders/1.json
  def destroy
    @food_order.destroy
    respond_to do |format|
      format.html { redirect_to orders_path, notice: 'Food order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_order
      @food_order = FoodOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_order_params
      params.require(:food_order).permit(:food_id, :order_id, :quantity)
    end
end

app/helpers/food_orders_helper.rb
module FoodOrdersHelper
end

app/views/food_orders/_form.html.slim
= simple_form_for(@food_order) do |f|
  = f.error_notification

  .form-inputs
    = f.association :food, as: :check_boxes, collection: Food.order(:name)
    = f.association :order
    = f.number_field :quantity

  br
  .form-actions
    = f.button :submit, class: "btn btn-success"

app/views/food_orders/edit.html.slim
h1 Editing food_order

== render 'form'

=> link_to 'Show', @food_order
'|
=< link_to 'Back', food_orders_path

app/views/food_orders/index.html.slim
h1 Listing food_orders

table
  thead
    tr
      th Food
      th Order
      th Quantity
      th
      th
      th

  tbody
    - @food_orders.each do |food_order|
      tr
        td = food_order.food
        td = food_order.order
        td = food_order.quantity
        td = link_to 'Show', food_order
        td = link_to 'Edit', edit_food_order_path(food_order)
        td = link_to 'Destroy', food_order, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Food order', new_food_order_path

app/views/food_orders/new.html.slim
h1 New food_order

== render 'form'

= link_to 'Back', food_orders_path

app/views/food_orders/show.html.slim
p#notice = notice

p
  strong Food:
  = @food_order.food
p
  strong Order:
  = @food_order.order
p
  strong Quantity:
  = @food_order.quantity

=> link_to 'Edit', edit_food_order_path(@food_order)
'|
=< link_to 'Back', food_orders_path