config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :kitchen
  resources :food_orders
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :food_orders, dependent: :destroy
  validates :table, :status, :name, presence: true
  after_create_commit :broadcast_create_order
  after_update_commit :broadcast_update_order

  TABLES = 1..20
  WAITERS = ["Mozo1","Mozo2","Mozo3","Mozo4","Mozo5"]



  def broadcast_create_order
    @order = Order.find(self.id)
    ActionCable.server.broadcast "web_notifications_channel",
                                 message: html_new_order_chef(@order)
  end
  def broadcast_update_order
    @order = Order.find(self.id)
    case @order.status
    when "Finalizado"
      ActionCable.server.broadcast "web_notifications_channel", message: html_update_finalizado(@order)
    when "Pendiente"
      ActionCable.server.broadcast "web_notifications_channel", message: html_update_agregar(@order)
    when "Cancelado"
      ActionCable.server.broadcast "web_notifications_channel", message: html_cancelar_pedido(@order)
    end



  end


  private

    def html_new_order_chef(order)
      # 'chef<div class="alert alert-success alert-dismissible" role="alert"><a aria-label="close" class="close" data-dismiss="alert" href="#"> ×</a><h2>Nuevo pedido '+order.id.to_s+'</h2></div>
      'chef<div id="accordion">
        <div class="card">
          <div class="card-header bg-success" id="headingOne" "bg-success">
            <h5 class="mb-0"><div class="title-card">
              <b>N:</b> <span>'+ order.id.to_s + '&nbsp; </span><b>Mozo:</b> <span>'+ order.name + '&nbsp; </span><b>Mesa:</b> <span>' + order.table.to_s + '&nbsp; </span> <b>Estado:</b> <span>' + order.status + '&nbsp; </span> <b>Actualizado</b> <span>'+ order.updated_at.strftime('%H:%M %d-%m-%y')+'</span>
            </div>
            <span>&nbsp; </span>' +
            ActionController::Base.helpers.link_to("Finalizar orden", Rails.application.routes.url_helpers.kitchen_path(order, order: {status: "Finalizado"}), class: "btn btn-success", remote: true, method: :put) +
          '</h5>
        </div>
        <div aria-labelledby="headingOne" class="collapse show" data-parent="#accordion" id="collapseOne">
          <div class="card-body">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Plato</th>
                  <th>Estado</th>
                  <th>Cantidad</th>
                </tr>
              </thead>' + food_order_select(order) +
            '</table>
          </div>
        </div>
       </div>
      </div>' + '<script>toastr.success("Nueva orden N ' + order.id.to_s + '");</script>'
    end
    def food_order_select(order)
      strings = order.food_orders.map do |food_order|
        '<tbody> <tr>
            <th>' + food_order.food.name + '</th>
            <th>' + food_order.status + ' </th>
            <th>' + food_order.quantity.to_s + ' </th>
        </tbody>'
      end
      strings.join
    end
    def html_update_finalizado(order)
      'mozo<script>toastr.success("Orden N ' + order.id.to_s+ ' finalizado revisar Estados Finalizados");</script>'
      # 'mozo<div class="alert alert-success alert-dismissible" role="alert"><a aria-label="close" class="close" data-dismiss="alert" href="#"> ×</a><h2>Pedido ' +order.id.to_s+ ' finalizado revisar Estados Finalizados</h2>
      #   <h4><b>N:</b> <span>'+ order.id.to_s + '&nbsp; </span><b>Mozo:</b> <span>'+ order.name + '&nbsp; </span><b>Mesa:</b> <span>' + order.table.to_s + '&nbsp; </span> <b>Estado:</b> <span>' + order.status + '&nbsp; </span> <b>Actualizado</b> <span>'+ order.updated_at.strftime('%H:%M %d-%m-%y')+'</span></h3>
      # </div>'
    end
    def html_update_agregar(order)
      # 'chef<div class="alert alert-success alert-dismissible" role="alert"><a aria-label="close" class="close" data-dismiss="alert" href="#"> ×</a><h2>Se agregan platos a la orden ' + order.id.to_s + '</h2></div>
      'chef<div id="accordion">
        <div class="card">
          <div class="card-header bg-success" id="headingOne" >
            <h5 class="mb-0"><div class="title-card">
              <b>N:</b> <span>'+ order.id.to_s + '&nbsp; </span><b>Mozo:</b> <span>'+ order.name + '&nbsp; </span><b>Mesa:</b> <span>' + order.table.to_s + '&nbsp; </span> <b>Estado:</b> <span>' + order.status + '&nbsp; </span> <b>Actualizado</b> <span>'+ order.updated_at.strftime('%H:%M %d-%m-%y')+'</span>
            </div>
            <span>&nbsp; </span>' +
            ActionController::Base.helpers.link_to("Finalizar orden", Rails.application.routes.url_helpers.kitchen_path(order, order: {status: "Finalizado"}), class: "btn btn-success", remote: true, method: :put) +
          '</h5>
        </div>
        <div aria-labelledby="headingOne" class="collapse show" data-parent="#accordion" id="collapseOne">
          <div class="card-body">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Plato</th>
                  <th>Estado</th>
                  <th>Cantidad</th>
                </tr>
              </thead>' + food_order_select_status_pendiente(order) +
            '</table>
          </div>
        </div>
       </div>
      </div>' + '<script>toastr.success("Se agregan platos a la orden N ' + order.id.to_s + ' revisar");</script>'
    end
    def food_order_select_status_pendiente(order)
      strings = order.food_orders.order(status: :desc).map do |food_order|
        '<tbody> <tr>
            <th>' + food_order.food.name + '</th>
            <th>' + food_order.status + '</th>
            <th>' + food_order.quantity.to_s + ' </th>
        </tbody>'
      end
      strings.join
    end
    def html_cancelar_pedido(order)
      # 'chef<div class="alert alert-danger alert-dismissible" role="alert"><a aria-label="close" class="close" data-dismiss="alert" href="#"> ×</a><h2>Pedido ' +order.id.to_s+ ' Cancelado!! Detener su preparación</h2>
      #   <h4><b>N:</b> <span>'+ order.id.to_s + '&nbsp; </span><b>Mozo:</b> <span>'+ order.name + '&nbsp; </span><b>Mesa:</b> <span>' + order.table.to_s + '&nbsp; </span> <b>Estado:</b> <span>' + order.status + '&nbsp; </span> <b>Actualizado</b> <span>'+ order.updated_at.strftime('%H:%M %d-%m-%y')+'</span></h3>
      # </div>'
      'chef<script>toastr.error("Orden N ' +order.id.to_s+ ' Cancelado!! Detener su preparación");</script>'
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @status = pendiente_finalizado_params
    @orders = Order.where(status: @status).order(updated_at: :desc)
    @orders = @orders.paginate( :per_page => 10, :page => params[:page])
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @foods = Food.all.order(:name)
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
    @foods = Food.all.order(:name)
    @food_orders = @order.food_orders
  end

  # POST /orders
  # POST /orders.json
  def create
    if get_food_order_params == true
      @foods = Food.all.order(:name)
      @order = Order.new(order_params)
      flash[:error] = "La orden no puede estar vacía"
      render :new
    else
      if order_params.to_h["status"] != "Cancelado"
        @order = Order.new(order_params)
        @food_order = get_food_order_params
        @food_order.each{ |food_order| @order.food_orders.build(food_order)}
      end


      respond_to do |format|
        if @order.save
          flash[:success] = 'La orden ' + @order.id.to_s + ' fue creada satisfactoriamente'
          format.html { redirect_to action: "index"}
          format.json { render :show, status: :created, location: @order }
        else
          format.html { render :new }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
    end


  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    if get_food_order_params_update == true
      @foods = Food.all.order(:name)
      @order = Order.new(order_params)
      flash[:error] = "Debe agregar por lo menos un plato"
      render :new
    else
      if order_params.to_h["status"] != "Cancelado"
        @food_order = get_food_order_params
        @food_order.each{ |food_order| @order.food_orders.build(food_order)}
      end

      respond_to do |format|
        if @order.update(order_params)
          if @order.status == "Cancelado"
            flash[:error] = 'La orden ' + @order.id.to_s + ' fue cancelada'
          else
            flash[:success] = 'La orden ' + @order.id.to_s + ' fue actualizada satisfactoriamente'
          end
          format.html { redirect_to action: "index"}
          format.json { render :show, status: :ok, location: @order }
        else
          format.html { render :edit }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:table, :status, :name)
    end

    def food_order_params
      food_order_params = params.require(:order).permit({:food_orders => {}}).to_h
    end

    def get_food_order_params_update
      if food_order_params["food_orders"].to_h == {} && order_params.to_h["status"] == "Pendiente"
        true
      else
        false
      end
    end

    def get_food_order_params
      if food_order_params["food_orders"].to_h == {} && order_params.to_h["status"] == "Pendiente"
        return true
      end
      quantity = food_order_params["food_orders"]["quantity"].select{|quantity| quantity.to_i > 0}
      food_id = food_order_params["food_orders"]["food"]
      food_id.each_with_index.map{|id, index| {"food_id" => id, "quantity" => quantity[index], "status" => "Pendiente"}}
    end

    def pendiente_finalizado_params
      if params[:status]
        params[:status]
      else
        "Pendiente"
      end
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
  def food_id_exist?(food, food_orders)
    food_orders.each do |food_order|
      if food_order.food_id == food.id
        return true
      end
    end
    false
  end
  def food_order_quantity(food, food_orders)
    food_orders.each do |food_order|
      if food_order.food_id == food.id
        return food_order.quantity
      end
    end
  end
  def flash_class(level)
    case level
        when "notice" then "alert alert-info"
        when "success" then "alert alert-success"
        when "error" then "alert alert-danger"
        when "alert" then "alert alert-danger"
    end
  end
  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
      flash_messages.join("\n").html_safe
  end
end

app/views/orders/_form.html.slim
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      h2 = "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      ul
        - @order.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :table
    = f.number_field :table
  .field
    = f.label :status
    = f.text_field :status
  .actions = f.submit

app/views/orders/edit.html.slim
= form_for @order do |f|
  .row
    .field.col-md-3.col-6
      = f.label "Mozo"
      = f.collection_select :name, Order::WAITERS, :to_s, :to_s, :include_blank => false
    .field.col-md-3.col-6
      = f.label "Mesa"
      = f.collection_select :table, Order::TABLES, :to_s, :to_s, :include_blank => false
    .field
      = f.text_field :status, {value: "Pendiente", style: "#{'display:none'}"}
    .actions.col-6
      = f.submit "Actualizar orden", class: "btn btn-success"
  br
  .row
    - @foods.each do |food|
      .col-xs-2.col-sm-6.col-md-3
        .card
          img.card-img-top alt=("Card image cap") src="#{image_url("#{food.photo}")}" /
          .card-body
            .input-group.mb-3
              .input-group-prepend
                .input-group-text
                  = f.fields_for :food_orders do |food_order|
                    .food-order-food
                      input[ type="checkbox" value="#{food.id}" name="order[food_orders][food][]"
                         id="#{"order_food_orders_food_"+ food.id.to_s}"]
                      input[ multiple="multiple" min="1" value="0" type="number" name="order[food_orders][quantity][]"
                        id="#{"order_food_orders_quantity_" + food.id.to_s}" disabled]

                      / - if food_id_exist?(food, @food_orders)
                      /   input[ type="checkbox" value="#{food.id}" name="order[food_orders][food][]"
                      /      id="#{"order_food_orders_food_"+ food.id.to_s}" checked="checked"]
                      /   input[ multiple="multiple" min="1" value="#{food_order_quantity(food, @food_orders)}" type="number" name="order[food_orders][quantity][]"
                      /     id="#{"order_food_orders_quantity_" + food.id.to_s}"]
                      / - else
                      /   input[ type="checkbox" value="#{food.id}" name="order[food_orders][food][]"
                      /      id="#{"order_food_orders_food_"+ food.id.to_s}"]
                      /   input[ multiple="multiple" min="1" value="0" type="number" name="order[food_orders][quantity][]"
                      /     id="#{"order_food_orders_quantity_" + food.id.to_s}" disabled]

            h5.card-title
              = food.name
            p.card-text
              = "S/ " + food.price.to_s

app/views/orders/index.html.slim
h1.same-line Ordenes vista del mozo
= link_to 'Nueva orden', new_order_path, class: "btn btn-success btn-align"
br
h3.same-line Estados
- if @status == "Pendiente"
  = link_to 'Pendientes', orders_path(status: "Pendiente"), class: "btn btn-primary btn-align"
  = link_to 'Finalizados', orders_path(status: "Finalizado"), class: "btn btn-outline-primary btn-align"
  = link_to 'Cancelados', orders_path(status: "Cancelado"), class: "btn btn-outline-primary btn-align"
- if @status == "Finalizado"
  = link_to 'Pendientes', orders_path(status: "Pendiente"), class: "btn btn-outline-primary btn-align"
  = link_to 'Finalizados', orders_path(status: "Finalizado"), class: "btn btn-primary btn-align"
  = link_to 'Cancelados', orders_path(status: "Cancelado"), class: "btn btn-outline-primary btn-align"
- if @status == "Cancelado"
  = link_to 'Pendientes', orders_path(status: "Pendiente"), class: "btn btn-outline-primary btn-align"
  = link_to 'Finalizados', orders_path(status: "Finalizado"), class: "btn btn-outline-primary btn-align"
  = link_to 'Cancelados', orders_path(status: "Cancelado"), class: "btn btn-primary btn-align"
= will_paginate @orders, renderer: WillPaginate::ActionView::BootstrapLinkRenderer
br
= custom_bootstrap_flash
/ - flash.each do |name, msg|
/   #alert class = "#{flash_class(name)} alert-dismissible" role="alert"
/     a.close aria-label="close" data-dismiss="alert" href="#"  ×
/     h2 = msg
#kitchen value="mozo"
#accordion
  - @orders.each do |order|
    .card
      = content_tag(:div, id: "heading" + order.id.to_s, class: "card-header")
        h5.mb-0
          .title-card
            b> N:
            span> #{order.id} &nbsp;
            b> Mozo:
            span> #{order.name} &nbsp;
            b> Mesa:
            span> #{order.table} &nbsp;
            b> Estado:
            span> #{order.status} &nbsp;
            b> Actualizado
            span> #{order.updated_at.strftime('%H:%M %d-%m-%y')}
          span> &nbsp; &nbsp;
          - if @status == "Pendiente"
            = link_to "Agregar", edit_order_path(order), class: "btn btn-success"
            span> &nbsp; &nbsp;
            = link_to "Cancelar", order_path(order, order: {status: "Cancelado"}), class: "btn btn-danger", method: :put
          - if @status == "Finalizado"
            = link_to "Agregar", edit_order_path(order), class: "btn btn-success"
            span> &nbsp; &nbsp;
            = link_to "Cancelar", order_path(order, order: {status: "Cancelado"}), class: "btn btn-danger", method: :put

      = content_tag(:div, id: "collapse" + order.id.to_s, class: "collapse show", 'aria-labelledby' => "heading" + + order.id.to_s, 'data_parent' => "#accordion")
        .card-body
          table.table.table-striped.table-hover
            thead
              tr
                th Plato
                th Estado
                th Cantidad
                th Precio
                / th
                / th
            - order.food_orders.includes(:food).each do |food_order|
              tbody
                  th #{food_order.food.name}
                  th #{food_order.status}
                  th #{food_order.quantity}
                  th #{"S/"+food_order.food.price.to_s}
                  / th = link_to "Editar", food_order, class: "btn btn-warning", data: { confirm: 'Are you sure?' }, method: :delete
                  / th = link_to "Eliminar", food_order, class: "btn btn-danger", data: { confirm: 'Are you sure?' }, method: :delete
            tbody
                  th Total
                  th
                  th
                  th= "S/" + order.food_orders.map{|food_order| food_order.quantity * food_order.food.price}.reduce(0, :+).to_s
                  / th

app/views/orders/new.html.slim
= form_for @order do |f|
  - if flash[:error]
    #error_explanation
    .alert.alert-danger.alert-dismissible role="alert"
      a.close aria-label="close" data-dismiss="alert" href="#"  ×
      h2 = "Un error encontrado"
      ul
        li = flash[:error]
  .row
    .field.col-md-3.col-6
      = f.label "Mozo"
      = f.collection_select :name, Order::WAITERS, :to_s, :to_s, :include_blank => false
    .field.col-md-3.col-6
      = f.label "Mesa"
      = f.collection_select :table, Order::TABLES, :to_s, :to_s, :include_blank => false
    .field
      = f.text_field :status, {value: "Pendiente", style: "#{'display:none'}"}
    .actions.col-6
      = f.submit "Crear orden", class: "btn btn-success", data: { confirm: '¿Esta seguro de crear una nueva orden? una vez creada solo se le podrá cancelar o agregar nuevos platos' }
  br
  .row
    - @foods.each do |food|
      .col-xs-2.col-sm-6.col-md-3
        .card
          img.card-img-top alt=("Card image cap") src="#{image_url("#{food.photo}")}" /
          .card-body
            .input-group.mb-3
              .input-group-prepend
                .input-group-text
                  = f.fields_for :food_orders do |food_order|
                    / = food_order.check_box :food, {multiple: true, value: food.id}
                    .food-order-food
                      input[ type="checkbox" value="#{food.id}" name="order[food_orders][food][]"
                         id="#{"order_food_orders_food_"+ food.id.to_s}"]
                    input[ multiple="multiple" min="0" value="0" type="number" name="order[food_orders][quantity][]"
                        id="#{"order_food_orders_quantity_" + food.id.to_s}" disabled ]
            h5.card-title
              = food.name
            p.card-text
              = "S/ " + food.price.to_s
  .row
    .actions
      = f.submit "Crear orden", class: "btn btn-success", data: { confirm: '¿Esta seguro de crear una nueva orden? una vez creada solo se le podrá cancelar o agregar nuevos platos' }

app/views/orders/show.html.slim
p#notice = notice

p
  strong Table:
  = @order.table
p
  strong Status:
  = @order.status

=> link_to 'Edit', edit_order_path(@order)
'|
=< link_to 'Back', orders_path