config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :kitchen
  resources :food_orders
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :food_orders
  validates :name, :price, :photo, presence: true

  def to_s
    "#{id}"
  end


end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :description, :price)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.slim
= form_for @food do |f|
  - if @food.errors.any?
    #error_explanation
      h2 = "#{pluralize(@food.errors.count, "error")} prohibited this food from being saved:"
      ul
        - @food.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :price
    = f.number_field :price
  .actions = f.submit

app/views/foods/edit.html.slim
h1 Editing food

== render 'form'

=> link_to 'Show', @food
'|
=< link_to 'Back', foods_path

app/views/foods/index.html.slim
h1 Listing foods

table
  thead
    tr
      th Name
      th Description
      th Price
      th
      th
      th

  tbody
    - @foods.each do |food|
      tr
        td = food.name
        td = food.description
        td = food.price
        td = link_to 'Show', food
        td = link_to 'Edit', edit_food_path(food)
        td = link_to 'Destroy', food, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Food', new_food_path

app/views/foods/new.html.slim
h1 New food

== render 'form'

= link_to 'Back', foods_path

app/views/foods/show.html.slim
p#notice = notice

p
  strong Name:
  = @food.name
p
  strong Description:
  = @food.description
p
  strong Price:
  = @food.price

=> link_to 'Edit', edit_food_path(@food)
'|
=< link_to 'Back', foods_path