config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :kitchen
  resources :food_orders
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    / meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    / meta name="description" content=""
    / meta name="author" content=""
    title PCM-Prueba
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'

  body
    nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
      .container
        a.navbar-brand href="#{root_path}"
          = fa_icon "cutlery"
        button.navbar-toggler aria-controls="navbarNavDropdown" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNavDropdown" data-toggle="collapse" type="button"
          span.navbar-toggler-icon
        #navbarNavDropdown.collapse.navbar-collapse
          ul.navbar-nav
            li.nav-item.dropdown
              a#navbarDropdownMenuLink.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#"
                | Mozos
              .dropdown-menu aria-labelledby="navbarDropdownMenuLink"
                a.dropdown-item href="#{orders_path}"  Ordenes
                a.dropdown-item href="#{new_order_path}"  Nueva orden
            li.nav-item.dropdown
              a#navbarDropdownMenuLink.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#"
                | Chefs
              .dropdown-menu aria-labelledby="navbarDropdownMenuLink"
                a.dropdown-item href="#{kitchen_index_url}"  Ordenes

    .container
      br
      = yield